### ISSUE TITLE
failed to compile because of babel-loader

### ISSUE THREAD

**Issue by LordST95** [IjzerenHein/react-native-bundle-visualizer#11]
Hi, when I want to run, I get the error below
(node:25862) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

 ERROR  Failed to compile.

./node_modules/haul/src/vendor/polyfills/String.prototype.es6.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
...............

what should I do?

**Comment by LordST95** [comment]
![screenshot from 2018-09-18 14-57-19](https://user-images.githubusercontent.com/10278253/45681661-55257d00-bb53-11e8-9ff2-73fcb064354e.png)
Node: v8.11.1
RN: 0.56
this is the screenShot and more information, I guess the problem is with haul but I can't figure out how to handle it :))

**Comment by IjzerenHein** [comment]
Yes it indeed seems to be with Haul. Were you using Haul already in this project?
Also, you could try installing the latest version of haul into your project and see whether that solves the problem. Let me know whether that works, I might need to release an update which uses the latest Haul bundlers.
Cheers

**Comment by LordST95** [comment]
No, I just use the default bundler of RN, when I search about this error, some guys were said that changing the configurations of their webPack's config file could solve this, and because I have not experience in working with webpack and haul, I gues maybe you could help me.

**Comment by IjzerenHein** [comment]
Well, what I would try when I was you, is to install the latest Haul bundler and try to run it with your project. And when you run into a problem, post an issue on the Haul repo with some detailed information. Probably people over there will be able to help you.

**Comment by LordST95** [comment]
Ok, thanks for ur help, GoodLuck ;)
