### ISSUE TITLE
Bundle size does not reflect App Store size

### ISSUE THREAD

**Issue by tomskopek** [IjzerenHein/react-native-bundle-visualizer#121]
After running:

`yarn run react-native-bundle-visualizer`

I get this as output:

```
Bundle is 7.82 MB in size (unchanged since last run)
Unable to map 1252691/8196479 bytes (15.28%)
```

However, our app in the iOS app store is around 62 MB

Am I missing something? Is bundle size a different thing than the app size in the app store?

**Comment by effektsvk** [comment]
Bundle size is only the javascript part of your app, it's the file that is created by Metro bundler. Rest of the app consists of native packages, all your assets such as images and app icon, hermes (javascript engine used by React Native), and so on.

**Comment by tomskopek** [comment]
Thanks @effektsvk - any idea of a tool to profile the other stuff?
We don't have many images, all are compressed and total size of images is < 400kb
I'm trying to figure out where the bloat is

**Comment by effektsvk** [comment]
I'm not really sure, there are some tips in the [Apple docs](https://developer.apple.com/documentation/xcode/reducing-your-app-s-size/) but I didn't try that yet. Maybe you could check `ios/Pods` folder to see if there are any big dependencies (these will be compiled down to a smaller size in final app though) but you'll probably need all of them anyway.

**Comment by effektsvk** [comment]
Hey @tomskopek, I looked into it a bit. One of the ways you can analyze your iOS build is to do an archive (in your Xcode project you can do `Product > Archive`. When the archive is done, you can find it in the Finder by right clicking on it. You can find your app in `Products/Applications`, go inside `YourApp.app` by right clicking and choosing `Show Package Contents` and you can dig in there to see if you find something 😅

Just small note, I found out that Hermes (the JavaScript engine that React Native uses) is pretty huge, it actually takes up around 500 MB in my app. So if you are using somewhat recent version of React Native, you'll probably notice that too. It's located in the `Frameworks/hermes.framework` in your `.app` file.

**Comment by rodperottoni** [comment]
you're likely not gonna be able to find a ~62mb file because it simply doesn't exist in your machine - that's Apple's App Thinning doing its thing in their infrastructure. The file you upload to Apple gets separated into multiple different bundles optimized for each platform that may at some point download it. This means some devices will see bigger bundles than others (e.g. iPads will have heavier bundles due to the image sizes that get included in them, such as @3x.pngs).

**Comment by tomskopek** [comment]
Oh, that's very interesting @rodperottoni. I never thought about it that way and that makes more sense!
