### ISSUE TITLE
Receiving error regarding react-hot-loader

### ISSUE THREAD

**Issue by gprocell927** [IjzerenHein/react-native-bundle-visualizer#14]
Hi!
I wanted to try running this, but I run into an error
`Can't resolve 'react-hot-loader' in '/Users/gabi/project_name/node_modules/react-timer-mixin'` when I run `yarn run react-native-bundle-visualizer`.

I tried uninstalling and reinstalling my node modules, and my current node version is 11.10.0. React native version 0.57.8

Any suggestions? 😅 
Thanks in advance!

**Comment by IjzerenHein** [comment]
Hmm, no idea to be honest. Most of the time it's an issue with the haul bundler. Could you check whether your project builds with haul and or not, and what errors you are getting?

**Comment by gprocell927** [comment]
@ljzerenHein (thanks for the response!), the project isn't building with haul and the only error I was getting was the one that would say `Can't resolve 'react-hot-loader'` when I would try to run `yarn run react-native-bundle-visualizer`. Afterward, it would just stop running altogether. 🤔

**Comment by IjzerenHein** [comment]
Do you have `react-hot-loader` in your babelrc?

**Comment by gprocell927** [comment]
We don't have a babelrc file or react-hot-loader. We're just using a `babel.cofig.js` file.

So I guess I should look into those as well? 🤔

**Comment by IjzerenHein** [comment]
What are you using the `babel.config.js` file for? Can you share its contents here?

**Comment by radeno** [comment]
@gprocell927 i got same issues even with `haul`.
You need to add `react-dom` and `react-hot-loader` to devDependencies

**Comment by radeno** [comment]
Same issue here https://github.com/callstack/haul/issues/508 looks like it is not fixed yet

**Comment by amed** [comment]
Same issue here, BUT what is noticeable is , the hot reloading issue is related to a dir level above.

```
Field 'browser' doesn't contain a valid alias configuration
             /Users/amed/mobile/node_modules/react-hot-loader.js doesn't exist
         /Users/amed/node_modules/react-hot-loader doesn't exist
       .ios.js
```

**Comment by IjzerenHein** [comment]
Hi, I've released a new version which fixes the issue regarding the `react-hot-loader`. It basically installs these two dependencies, which are apparently needed by Haul.
Also, it adds support for transpilation of the new @react-native-community libs, which are shipped as flow-code and therefore require transpilation.
https://github.com/IjzerenHein/react-native-bundle-visualizer/releases/tag/v1.4.1
