### ISSUE TITLE
missing script: react-native-bundle-visualizer

### ISSUE THREAD

**Issue by ankitsehgal94** [IjzerenHein/react-native-bundle-visualizer#15]
npm run  react-native-bundle-visualizer is showing error  missing script: react-native-bundle-visualizer

**Comment by IjzerenHein** [comment]
Please read the documentation more carefully next time. When using `npm` you need to use:
`./node_modules/.bin/react-native-bundle-visualizer`

**Comment by IjzerenHein** [comment]
Did that help?

**Comment by ankitsehgal94** [comment]
Thanks, bro. It helped.

**Comment by IjzerenHein** [comment]
Cool 👍 Can you close this issue?
