### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by rahamin1** [IjzerenHein/react-native-bundle-visualizer#17]
I am using Windows 10.

I have done installation by:  
`npm install --save-dev react-native-bundle-visualizer`

And when I try to run the program using:
`./node_modules/.bin/react-native-bundle-visualizer`

I get the message: 

> The system cannot find the path specified.

If I try to run other programs in the same path, like:
`.\node_modules\.bin\which`
It is working properly.

**Comment by IjzerenHein** [comment]
That looks like a Windows specific problem. Path separators are usually denoted using the `/` characters on Node.js environments. You are probably not running the script in the correct environment/context

**Comment by khalidahmedshalabi** [comment]
Have you figured out a solution to this? @rahamin1 Post it please

**Comment by rahamin1** [comment]
No, I haven't
