### ISSUE TITLE
How to configure this so it actually works?

### ISSUE THREAD

**Issue by skizzo** [IjzerenHein/react-native-bundle-visualizer#18]
Hi,

I'm trying visualize my app bundle (duh) and followed your instructions of `npm install --save-dev react-native-bundle-visualizer` and then `./node_modules/.bin/react-native-bundle-visualizer` for my React Native (`0.59.10`) app.

Unfortunately, all that happens is that I get about a kazillion errors instead of a result, although my project runs fine on both iOS and Android. The [**terminal output**](https://gist.github.com/skizzo/8f626915f385152e4a54a9cedb0a2c50) doesn't really help me figure out what's going on since it's about 80.000 lines long (yeah, it's quite a huge project).

My **`.babelrc`** file looks like this:
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "env": {
    "production": {
      "plugins": [ ["transform-remove-console", { "exclude": [ "error", "warn"] }] ]
    }
  }  
}
```

Any ideas what's going on here? Thanks.

**Comment by IjzerenHein** [comment]
Hi, I just ran a test on an extensive project running react-native `0.59.10` and that ran fine on my machine. So it doesn't seem to be related with react-native 0.59.10.

In order to isolate the problem, can you provide the following information:
- Are you using typescript?
- Are you using Windows or a Mac?
- Which node.js version are you using?
- Do you have a haul-config file in your project, and if so please share it here?

In the log it says it can't find `Screen.js`. Can you confirm that this file indeed exists and that it has the exact same casing in the file-name as is used in the `import` statement?

**Comment by skizzo** [comment]
Hi @IjzerenHein, thanks for your quick reply. To answer your questions:

*Are you using typescript?* - Nope.

*Are you using Windows or a Mac?* - Mac.

*Which node.js version are you using?* - `v8.12.0`

*Do you have a haul-config file in your project, and if so please share it here?* - Not as far as I know.

Yes, the `Screen.js` file exists, as I said, I'm able to use all of these files mentioned in the errors in my app perfectly. Any other ideas? :)

**Comment by IjzerenHein** [comment]
Okay.

How did you create your project, did you use `react-native init` or some other template?

**Comment by skizzo** [comment]
I used `react-native init`.

**Comment by IjzerenHein** [comment]
I see. Well we're not getting closer that's for sure. :) Is there anything specific about your project that is worth mentioning? Or is there anything specific in the files that are failing that you could think of? Can you share one of the failing files (including filename)?

**Comment by IjzerenHein** [comment]
Hi, a new release has been published: https://github.com/IjzerenHein/react-native-bundle-visualizer/releases/tag/v1.4.2
Could you check whether that solves any problems for you?

**Comment by skizzo** [comment]
Hello good Sir!
Thanks very much for the update, but unfortunately it doesn't work with `v1.4.2` either, the terminal output is [in this gist](https://gist.github.com/skizzo/81f2692b59a109e4d746e0e480345956) and looks pretty similar to the one from `v1.4.1`. 
Don't know, it must be something with the way my project is set up, I probably fucked up somewhere. If you don't think we can narrow down what's going wrong here, feel free to close this issue!

**Comment by IjzerenHein** [comment]
Alright, too bad! No lets keep this open for now.  I'm sure there is a good reason why stuff is breaking for you. Could you perhaps share the dependencies that you are using, perhaps that can shed light on the situation. Also, are you targeting any other platforms than Android and iOS?

**Comment by IjzerenHein** [comment]
Hi, a new version of react-native-bundle-visualizer is in the works which no longer uses Haul and should solve your problems as well (and is also a lot faster).
Could you try installing `react-native-bundle-visualizer@next` and see whether that solves your problem?

**Comment by lucianomlima** [comment]
> My **`.babelrc`** file looks like this:
> 
> ```
> {
>   "presets": ["module:metro-react-native-babel-preset"],
>   "env": {
>     "production": {
>       "plugins": [ ["transform-remove-console", { "exclude": [ "error", "warn"] }] ]
>     }
>   }  
> }
> ```

Are you not missing the `@babel/env` inside presets?

**Comment by skizzo** [comment]
> Hi, a new version of react-native-bundle-visualizer is in the works which no longer uses Haul and should solve your problems as well (and is also a lot faster).
> Could you try installing `react-native-bundle-visualizer@next` and see whether that solves your problem?

Hi and thanks for the update! I `npm install`ed the `@next` version, **and it works like a charm now**! I'm not getting the beautiful graphic shown in your README, but that doesn't matter to me at all.

![Screenshot 2019-08-12 at 08 56 50](https://user-images.githubusercontent.com/2892572/62849255-2d955100-bcdf-11e9-8901-f12607e9c8ee.png)

Thanks so much!

**Comment by lucianomlima** [comment]
> Hi and thanks for the update! I `npm install`ed the `@next` version, **and it works like a charm now**! I'm not getting the beautiful graphic shown in your README, but that doesn't matter to me at all.

It's because use different approaches. V1 uses webpack + Haul bundler.
V2 uses metro bundler + source-map-explorer.

**Comment by skizzo** [comment]
Ah, thanks for the insight @lucianomlima!

**Comment by xutm** [comment]
Hi, 

I have a try to use it (react-native-bundle-visualizer@next), but has errors.

I don't know how to solve it.

```
~/tomorrow/bulla(ft-upgrade-asgard*) » ./node_modules/.bin/react-native-bundle-visualizer                                                                                tianmingxu@tianmingxudeMacBook-Pro
Generating bundle...
Loading dependency graph, done.
(node:82298) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1 (EPERM): ./node_modules/.bin/react-native bundle --platform ios --dev false --entry-file ./src/index.js --bundle-output /var/folders/m2/y8dlrqbd4sqgz1m6txgp00ch0000gn/T/react-native-bundle-visualizer/bulla/ios.bundle --sourcemap-output /var/folders/m2/y8dlrqbd4sqgz1m6txgp00ch0000gn/T/react-native-bundle-visualizer/bulla/ios.bundle.map
    at makeError (/Users/tianmingxu/tomorrow/bulla/node_modules/react-native-bundle-visualizer/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/tianmingxu/tomorrow/bulla/node_modules/react-native-bundle-visualizer/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:82298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
------------------------------------------------------------
```

**Comment by IjzerenHein** [comment]
Hi. V2 has been released as official, I'm closing this now
