### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by maraujop** [IjzerenHein/react-native-bundle-visualizer#2]
Hi Hein,

Compilation fails without any error message to debug:

![captura de pantalla 2017-10-17 a las 9 58 49](https://user-images.githubusercontent.com/252257/31653146-cf4d2a28-b321-11e7-8995-93c6a09b23a7.png)

Thanks, cheers
Miguel

**Comment by maraujop** [comment]
BTW, I forgot to mention, that this happens also in a new react-native project created from scratch with RN 0.49.3

**Comment by IjzerenHein** [comment]
What version of node are you using?

**Comment by p3drosola** [comment]
I'm getting the same error with node 8.2.1 and react-native 0.49.3

**Comment by IjzerenHein** [comment]
Yikes. I have no idea what could be wrong there tbh. I'm pretty sure it's an error when `haul` is trying to bundle the code. I've just updated `react-native-bundle-visualizer` (to v1.1.0) to use the latest version of Haul. Could you try installing that? If that doesn't help, please follow the instructions on the haul site (`yarn run haul init`) and run `yarn run haul bundle --platform ios`. Also, haul creates a debug file (`haul-debug.log`) which may contain useful logs. Please dump that here.

**Comment by p3drosola** [comment]
I've  pulled the latest from github https://github.com/IjzerenHein/react-native-bundle-visualizer/commit/27b9270822f6c0f1797f40b57ae651f69c6ae5ee and I'm still getting the same error.

A plain haul bundle works fine. 

`./node_modules/.bin/haul bundle --verbose --prod --platform ios`

But when I pass in the config file it fails, and doesn't print anything to the `haul-debug.log` `./node_modules/.bin/haul bundle --verbose --prod --platform ios --config ./node_modules/react-native-bundle-visualizer/src/webpack.haul.js`

So I guess it's something in the config file or the visualizer plugin.

**Comment by p3drosola** [comment]
Ok I found the issue. Seems like RN moved to a single index.js entry point, and the webpack config is assuming platform specific entry points.

**Comment by IjzerenHein** [comment]
Ah of course. I read about it in the release notes but am still on .48 myself. I will see to it that this gets fixed. Thanks for finding the problem @p3drosola 👍

**Comment by IjzerenHein** [comment]
Hi, I've just released v1.20, it now works with react-native@0.49.x
