### ISSUE TITLE
[V2] I'm run some tests and I've figure out that after the first run, the nexts will use cache

### ISSUE THREAD

**Issue by lucianomlima** [IjzerenHein/react-native-bundle-visualizer#20]
Maybe enable or force put a `--reset-cache` to bundle step, avoid get generating the same results one after another (or try avoiding generate same bundle even when a change have made on source code).

**Comment by IjzerenHein** [comment]
Great idea, I'm gonna investigate that a bit further and probably at it.
Thanks!

**Comment by IjzerenHein** [comment]
Hi, I've been unable to reproduce this problem. What version of react-native are you using?

**Comment by IjzerenHein** [comment]
I've released a new `@next` (2.0.3) version which contains the option `--reset-cache`. It's disabled by default. Let me know whether that works for you.
Cheers

**Comment by lucianomlima** [comment]
> Hi, I've been unable to reproduce this problem. What version of react-native are you using?

I'm using RN@0.59.8. When I run the bundle visualizer in the first time, takes 3~5min, but if I change the code and run bundle visualizer again, generate same results but in some few seconds.

I'll test with the new version and try to mount an example repro later. Thanks!

**Comment by IjzerenHein** [comment]
Yeah that's react-native/metro using a cache. That's generally a good thing and for what I've seen it correctly generates the bundle whenever you change code in your project

**Comment by lucianomlima** [comment]
Nice. I'll close this issue because there is a way to disable cache. Thanks!
