### ISSUE TITLE
Visualizer script fails when package name is scoped

### ISSUE THREAD

**Issue by cameronbell** [IjzerenHein/react-native-bundle-visualizer#21]
I'm using v2. My RN app lives in a package within a monorepo, so the `name` field in the package.json is `@org/appName`. The script fails when trying to create the tmp directory because of the slash in the package name. I was able to run the script no problem by changing the package name, but it would be ideal if this package could accommodate this kind of package name.

**Comment by IjzerenHein** [comment]
Alright, good find! Will fix this in the next update, thanks for reporting this.

**Comment by ofiron01** [comment]
@IjzerenHein  I've created a PR #23  to fix this issue. Was able to reproduce and this PR resolves it.
@cameronbell

**Comment by IjzerenHein** [comment]
Awesome, thanks for the fix @ofiron01 👍 👍 
I've released a new version which includes the fix:
https://github.com/IjzerenHein/react-native-bundle-visualizer/releases/tag/v2.1.1

**Comment by ofiron01** [comment]
@IjzerenHein I can confirm the issue doesn't reproduce anymore

**Comment by IjzerenHein** [comment]
Awesome @ofiron01 !
@cameronbell let me know whether I can close this.
Cheers

**Comment by cameronbell** [comment]
Fixed for me as well. Thanks!
