### ISSUE TITLE
Cannot find module 'expo-asset/tools/hashAssetFiles'

### ISSUE THREAD

**Issue by Lerosen** [IjzerenHein/react-native-bundle-visualizer#37]
Hi,

I tried to use this tool on my Expo 36 project. I installed the package as a dev dependency but get the following error running `yarn run react-native-bundle-visualizer --expo managed`: Error: Cannot find module 'expo-asset/tools/hashAssetFiles'

I looked into the node_modules folder and expo-asset version 8.0.0 does not seem to contain the required file.

**Comment by IjzerenHein** [comment]
Huh interesting. There is a test for a plain Expo 36 project which does not suffer from this problem. Perhaps the problem lies in your custom babel or metro config. Could you share your babel and metro config?
