### ISSUE TITLE
Feature request: Option to predict Expo binary size

### ISSUE THREAD

**Issue by MichelDiz** [IjzerenHein/react-native-bundle-visualizer#6]
I see that the bundle has x KBytes, but would be interesting predict the final result in size. Just for analysis and planning.

**Comment by IjzerenHein** [comment]
You mean to predict to predict the whole app size, correct?

**Comment by MichelDiz** [comment]
yeah. Collect asset, code, and merge sizes with the size that the RN is by default.

**Comment by IjzerenHein** [comment]
But by building the APK you already would know the size wouldn't you? And what do you mean by "prediction in size" ?

**Comment by MichelDiz** [comment]
Yes, that would be the obvious thing to do. However, when we are producing the app let's say using Expo. The Expo does not generate an APK or IOS file. You will need to build to know.

How does this project serve to visualize the bundle, seeing sizes and etc. It would be useful to understand how the final build size would look.

And if you do not have a MACOS you would already have at hand how would build this when renting a computer with MacOS remotely.

**Comment by IjzerenHein** [comment]
Ok, so I guess what you mean is that you want to see the default Expo binary size + the bundle size, is that right?

**Comment by MichelDiz** [comment]
Yeah

**Comment by IjzerenHein** [comment]
Hi, as I don't use Expo, I don't have a need for this feature myself. Pull request are very welcome though ❤️

**Comment by IjzerenHein** [comment]
A new option `--expo managed|bare` has been added to bundle using the Expo settings and handle `.expo` files appropriately.
https://github.com/IjzerenHein/react-native-bundle-visualizer/releases/tag/v2.2.1

**Comment by IjzerenHein** [comment]
Closing this issue as predicting the binary size is out of scope for this package.
