### ISSUE TITLE
Support running using npx

### ISSUE THREAD

**Issue by brunolemos** [IjzerenHein/react-native-bundle-visualizer#8]
It should not be required to save as a dev dependency.

This should work: `npx react-native-bundle-visualizer`

But it gives: `/Users/me/.npm/_npx/83500/bin/react-native-bundle-visualizer: line 9: ./node_modules/.bin/haul: No such file or directory`

**Comment by IjzerenHein** [comment]
I've never heard of npx but it looks really cool.
Maybe if other people are also interested in this, I'll take a stab at supporting this.

**Comment by brunolemos** [comment]
It is built in on `npm` since 5.2 so I believe more and more people are starting to use it.

**Comment by Eyesonly88** [comment]
@brunolemos I have it as a devDependency and it works for me.

![image](https://user-images.githubusercontent.com/767013/49616309-442f2e00-fa15-11e8-8295-c86d999ff64b.png)


I had to add `react-hot-loader` as a devDep as well. I'm using `node v8.12.0` and `RN 57.1`

**Comment by IjzerenHein** [comment]
As of version 2.0.3 (pre-release) it is now possible to run this module using `npx`. Version 2 will be released shortly. You can already test it using `npx react-native-bundle-visualizer@next`.

**Comment by IjzerenHein** [comment]
V2 has been released as the new official version and `npx` is now the preferred method to run this package. Thanks for the suggestion 👍 
Closing this now, cheers
