### ISSUE TITLE
Module not found: Error: Can't resolve 'assets/image.png'

### ISSUE THREAD

**Issue by brunolemos** [IjzerenHein/react-native-bundle-visualizer#9]
Some places I have this code: `const image = require('assets/image.png')`

It works just fine, but when trying to use this lib it gives this error:
`Module not found: Error: Can't resolve 'assets/image.png'`

Changing to relative path will probably fix it, but it shouldn't be necessary.

**Comment by IjzerenHein** [comment]
Hi, since this library is just a thin layer on top of Haul, the problem (and probably solution) should be there. I'd try submitting an issue there or checking whether an issue already exists.
