### ISSUE TITLE
Nx compatible? 

### ISSUE THREAD

**Issue by flexbox** [IjzerenHein/react-native-bundle-visualizer#93]
Hey
Thank you for this cool library!

I had a look at #74 and I think I am running in —more or less— the same issue.

My stack is a React Native Library, created with Nx 
Here is an example
https://github.com/flexbox/react-native-nx-monorepo

Does anyone know how to make it run with [NX?](https://nx.dev/) ?

**Comment by MikeSpitz** [comment]
@flexbox Did you get anywhere with figuring out how to fix this or measure bundle size for react native apps on NX in the end? Currently hitting same issue as you are

**Comment by flexbox** [comment]
Hey @MikeSpitz 
Unfortunately no, I tried for a day a gave up on this. 

I will close for now because it seems out of scope and monorepo with Nx is a very different world Vs "classic" apps.

**Comment by keithchan-bowtie** [comment]
https://github.com/nrwl/nx/blob/master/packages/react-native/src/executors/bundle/schema.json
there is the `sourcemapSourcesRoot` to configure... not yet got time to try out. @flexbox
